// Autogenerated by scripts/deploy.js
export const TOKEN_ADDRESS = "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6";
export const DEX_ADDRESS = "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318";
export const CHAIN_ID = "31337";
