const { ethers, network, artifacts } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with the account:", deployer.address);

  // 1. Deploy Token A (NAO)
  const NaoToken = await ethers.getContractFactory("NAOTOKENERC20");
  const tokenA = await NaoToken.deploy("NAO Token", "NAO");
  await tokenA.waitForDeployment();
  const tokenAddress = await tokenA.getAddress();
  console.log("NAO Token deployed to:", tokenAddress);

  // 2. Deploy DEX (NAO + ETH)
  const SimpleDEX = await ethers.getContractFactory("SimpleDEX");
  const dex = await SimpleDEX.deploy(tokenAddress);
  await dex.waitForDeployment();
  const dexAddress = await dex.getAddress();
  console.log("SimpleDEX deployed to:", dexAddress);

  // 3. Liquidità iniziale: 100 NAO + 1 ETH
  const amountA = ethers.parseEther("100");
  const amountETH = ethers.parseEther("1");
  const deadline = (await ethers.provider.getBlock("latest")).timestamp + 600;

  await (await tokenA.approve(dexAddress, amountA)).wait();
  await (await dex.addLiquidity(amountA, 0, 0, deadline, { value: amountETH })).wait();
  console.log("Initial liquidity added: 100 NAO + 1 ETH");

  // 4. Salva gli indirizzi per interact.js o per un frontend
  const { chainId } = await ethers.provider.getNetwork();
  const deployment = {
    network: network.name,
    chainId: chainId.toString(),
    deployer: deployer.address,
    tokenA: tokenAddress,
    dex: dexAddress,
    deployedAt: new Date().toISOString()
  };
  const file = path.join(__dirname, "..", "deployed-contract.json");
  fs.writeFileSync(file, JSON.stringify(deployment, null, 2));
  console.log("Deployment info saved to deployed-contract.json");

  // 5. Esporta configurazione e ABI nel frontend client
  const clientContractsDir = path.join(__dirname, "..", "client", "src", "contracts");
  fs.mkdirSync(clientContractsDir, { recursive: true });

  const configContent = `// Autogenerated by scripts/deploy.js
export const TOKEN_ADDRESS = "${tokenAddress}";
export const DEX_ADDRESS = "${dexAddress}";
export const CHAIN_ID = "${chainId}";
`;
  fs.writeFileSync(path.join(clientContractsDir, "config.js"), configContent);

  const tokenArtifact = await artifacts.readArtifact("NAOTOKENERC20");
  fs.writeFileSync(path.join(clientContractsDir, "token_abi.json"), JSON.stringify(tokenArtifact.abi, null, 2));
  const dexArtifact = await artifacts.readArtifact("SimpleDEX");
  fs.writeFileSync(path.join(clientContractsDir, "dex_abi.json"), JSON.stringify(dexArtifact.abi, null, 2));
  console.log("Exported contract addresses & ABIs to client/src/contracts/");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
