const { ethers, artifacts } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("Deploying contracts with the account:", deployer.address);

  // 1. Deploy Staking Token (NAO)
  const MockERC20 = await ethers.getContractFactory("NAOTOKENERC20");
  const naoToken = await MockERC20.deploy("NAO Token", "NAO");
  await naoToken.waitForDeployment();
  const tokenAddress = await naoToken.getAddress();
  console.log("NAO Token deployed to:", tokenAddress);

  // 2. Deploy Staking Contract (Uses NAO for both Staking and Rewards)
  const Staking = await ethers.getContractFactory("Staking");
  const staking = await Staking.deploy(tokenAddress, tokenAddress);
  await staking.waitForDeployment();
  const stakingAddress = await staking.getAddress();
  console.log("Staking Contract deployed to:", stakingAddress);

  // 3. Setup iniziale
  // Finanzia il contratto di staking con NAO Tokens per le ricompense
  const rewardAmount = ethers.parseEther("100000");
  await naoToken.approve(stakingAddress, rewardAmount);
  await staking.depositRewards(rewardAmount);
  console.log("Deposited 100000 NAO into Staking contract for rewards");

  // 4. Esporta la configurazione e gli ABI nel frontend client
  const clientContractsDir = path.join(__dirname, "..", "client", "src", "contracts");
  if (!fs.existsSync(clientContractsDir)) {
    fs.mkdirSync(clientContractsDir, { recursive: true });
  }

  const configContent = `// Autogenerated by scripts/deploy.js
export const TOKEN_ADDRESS = "${tokenAddress}";
export const STAKING_ADDRESS = "${stakingAddress}";
`;
  fs.writeFileSync(path.join(clientContractsDir, "config.js"), configContent);

  const tokenArtifact = await artifacts.readArtifact("NAOTOKENERC20");
  fs.writeFileSync(
    path.join(clientContractsDir, "token_abi.json"),
    JSON.stringify(tokenArtifact.abi, null, 2)
  );

  const stakingArtifact = await artifacts.readArtifact("Staking");
  fs.writeFileSync(
    path.join(clientContractsDir, "staking_abi.json"),
    JSON.stringify(stakingArtifact.abi, null, 2)
  );

  console.log("Exported contract addresses & ABIs to client/src/contracts/");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

